# Generated by Django 5.2.2 on 2025-06-06 20:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варіанта')),
            ],
            options={
                'verbose_name': 'Варіант голосування',
                'verbose_name_plural': 'Варіанти голосування',
            },
        ),
        migrations.CreateModel(
            name='VotedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='Нікнейм')),
            ],
            options={
                'verbose_name': 'Проголосований користувач',
                'verbose_name_plural': 'Проголосовані користувачі',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_nickname', models.CharField(max_length=100, verbose_name='Нікнейм голосуючого')),
                ('score', models.IntegerField(verbose_name='Оцінка (бали)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час голосування')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.option', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоси',
            },
        ),
    ]
